Finish commands and installation script

diff --git a/scripts/dotfiles b/scripts/dotfiles
--- a/scripts/dotfiles
+++ b/scripts/dotfiles
@@ -26,10 +26,11 @@ dotfiles_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Create symlinks from .dotfiles to home directory.\n" "stow-dotfiles            "
-  printf "  %s   Create symlink for VSCode settings.json.\n" "symlink-vscode           "
-  printf "  %s   Install VSCode extensions from .dotfiles/.config/vscode/extesions.txt.\n" "install-vscode-extensions"
-  printf "  %s   Install extesion and add it to from .dotfiles/.config/vscode/extesions.txt.\n" "install-vscode-extension "
+  printf "  %s   Create symlinks from .dotfiles to home directory.\n" "stow-dotfiles                "
+  printf "  %s   Create symlink for VSCode settings.json.\n" "symlink-vscode               "
+  printf "  %s   Install VSCode extensions from .dotfiles/.config/vscode/extesions.txt.\n" "install-vscode-extensions    "
+  printf "  %s   Install extesion and add it to from .dotfiles/.config/vscode/extesions.txt.\n" "install-vscode-extension     "
+  printf "  %s   Install extesion and add it to from .dotfiles/.config/vscode/extesions.txt.\n" "update-vscode-extensions-list"
   echo
 
   # :command.long_usage
@@ -148,6 +149,29 @@ dotfiles_install_vscode_extension_usage() {
     # :argument.usage
     printf "  %s\n" "EXTENSION-ID"
     printf "    Extension ID to be installed.\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+dotfiles_update_vscode_extensions_list_usage() {
+  printf "dotfiles update-vscode-extensions-list - Install extesion and add it to from .dotfiles/.config/vscode/extesions.txt.\n\n"
+  printf "Alias: u-vscode-ext-list\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  dotfiles update-vscode-extensions-list\n"
+  printf "  dotfiles update-vscode-extensions-list --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -313,8 +337,10 @@ error() {
 
 # DOTFILES PATHS
 DOTFILES_DIR="$HOME/.dotfiles"
+
 VSCODE_CONFIG_DIR="$HOME/Library/Application Support/Code/User"
 VSCODE_CONFIG_FILE="settings.json"
+VSCODE_EXTENSIONS_FILE="$HOME/.dotfiles/.config/vscode/extensions.txt"
 
 # SSH PATH VARIABLES
 export SSH_PATH="$HOME/.ssh"
@@ -325,6 +351,81 @@ export SSH_CONFIG_FILE="$SSH_PATH/config"
 export DOTFILES_DIR="$HOME/dotfiles"
 export NIX_CONFIG_DIR="$HOME/.nix-config"
 export NIX_DARWIN_DIR="$HOME/.nix-darwin"
+
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# dotfiles completion                                      -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_dotfiles_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $''
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_dotfiles_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'install-vscode-extensions\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help --update -h -u")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'install-vscode-extension\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'symlink-vscode\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'stow-dotfiles\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'i-vscode-exts\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help --update -h -u")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'i-vscode-ext\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'sym-vscode\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_dotfiles_completions_filter "--help --version -h -v i-vscode-ext i-vscode-exts install-vscode-extension install-vscode-extensions s stow-dotfiles sym-vscode symlink-vscode")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'  complete -F _dotfiles_completions dotfiles'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
 
 # :command.command_functions
 # :command.function
@@ -377,25 +478,37 @@ dotfiles_install_vscode_extensions_command() {
   # src/install_vscode_extensions_command.sh
   #!/bin/bash
 
-  # Crear el directorio de configuración de VSCode si no existe
-  mkdir -p "$VSCODE_CONFIG_DIR"
+  update=${args[--update]}
 
-  # Eliminar el archivo de configuración existente si existe
-  if [ -f "$VSCODE_CONFIG_DIR/$VSCODE_CONFIG_FILE" ]; then
-    echo "Eliminando el archivo existente $VSCODE_CONFIG_FILE"
-    rm "$VSCODE_CONFIG_DIR/$VSCODE_CONFIG_FILE"
+  # Verificar si el archivo de extensiones existe
+  if [ ! -f "$VSCODE_EXTENSIONS_FILE" ]; then
+    warning "El archivo $VSCODE_EXTENSIONS_FILE no existe."
+    exit 1
   fi
 
-  # Crear el symlink
-  echo "Creando symlink para $VSCODE_CONFIG_FILE en $VSCODE_CONFIG_DIR"
-  ln -s "$DOTFILES_DIR/vscode/$VSCODE_CONFIG_FILE" "$VSCODE_CONFIG_DIR/$VSCODE_CONFIG_FILE"
+  # Leer el archivo y instalar las extensiones
+  info "Reading extensions file at $VSCODE_EXTENSIONS_FILE..."
+  while IFS= read -r extension; do
+    # Verificar que la línea no esté vacía y no comience con #
+    if [ -n "$extension" ] && [[ ! "$extension" =~ ^# ]]; then
+      section
 
-  # Confirmar el symlink
-  if [ -L "$VSCODE_CONFIG_DIR/$VSCODE_CONFIG_FILE" ]; then
-    echo "Symlink creado exitosamente."
-  else
-    echo "Hubo un problema al crear el symlink."
-  fi
+      if [[ -n "$update" ]]; then
+        info "Installing extension: $extension"
+        code --install-extension "$extension" --force
+
+      else
+
+        info "Installing extension: $extension"
+        warning "Probando"
+        code --install-extension "$extension"
+      fi
+
+    fi
+  done < "$VSCODE_EXTENSIONS_FILE"
+  section
+
+  success "Extesions installation completed successfully!."
 
 }
 
@@ -403,10 +516,77 @@ dotfiles_install_vscode_extensions_command() {
 dotfiles_install_vscode_extension_command() {
 
   # src/install_vscode_extension_command.sh
-  echo "# this file is located in 'src/install_vscode_extension_command.sh'"
-  echo "# code for 'dotfiles install-vscode-extension' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+  #!/bin/bash
+
+  extension_id=${args[extension-id]}
+
+  section
+  if code --list-extensions 2>/dev/null | grep -q "$extension_id"; then
+      warning "Extension '$extension_id' was already installed!."
+      info "Please, run 'dotfiles install-vscode-extensions --force' instead for updating to last version."
+  else
+    info "Installing extension '$extension_id'..."
+    code --install-extension "$extension_id"
+
+    if [ $? -eq 0 ]; then
+      success "Extension '$extension_id' succesfully installed!."
+    else
+      error "Error installing '$extension_id'."
+      exit 1
+    fi
+
+  fi
+
+  section
+  if ! grep -q "^$extension_id$" "$VSCODE_EXTENSIONS_FILE"; then
+    echo "$extension_id" >> "$VSCODE_EXTENSIONS_FILE"
+    echo "Extension '$extension_id' has been added to $VSCODE_EXTENSIONS_FILE."
+  else
+      warning "$extension_id was already in $VSCODE_EXTENSIONS_FILE!"
+  fi
+  section
+
+}
+
+# :command.function
+dotfiles_update_vscode_extensions_list_command() {
+
+  # src/update_vscode_extensions_list_command.sh
+  #!/bin/bash
+
+  CURRENT_DATE=$(date +%Y%m%d)
+
+  if [ -f "$VSCODE_EXTENSIONS_FILE" ]; then
+
+    warning "¿Are you sure you want to override '$VSCODE_EXTENSIONS_FILE'? (y/n)"
+    read -r respuesta
+
+    if [[ "$respuesta" == "y" || "$respuesta" == "Y" ]]; then
+
+      BACKUP_FILE="${VSCODE_EXTENSIONS_FILE}_${CURRENT_DATE}.bakup"
+      cp "$VSCODE_EXTENSIONS_FILE" "$BACKUP_FILE"
+      echo "Backup file saved at: $BACKUP_FILE"
+    else
+      info "Operation canceled. File was not overriden."
+      exit 0
+    fi
+  else
+    info "File '$VSCODE_EXTENSIONS_FILE' does not exists. No need for backup file."
+  fi
+
+  # Mostrar un mensaje indicando que se está actualizando la lista
+  info "Updating extensions list of VSCode at $VSCODE_EXTENSIONS_FILE..."
+
+  # Obtener la lista de extensiones instaladas y guardarlas en el archivo
+  code --list-extensions > "$VSCODE_EXTENSIONS_FILE"
+
+  # Verificar si la operación fue exitosa
+  if [ $? -eq 0 ]; then
+    success "Updated extension list saved at $VSCODE_EXTENSIONS_FILE"
+  else
+    error "There was an error updating extensions list."
+    exit 1
+  fi
 
 }
 
@@ -465,6 +645,13 @@ parse_requirements() {
       action="install-vscode-extension"
       shift
       dotfiles_install_vscode_extension_parse_requirements "$@"
+      shift $#
+      ;;
+
+    update-vscode-extensions-list | u-vscode-ext-list)
+      action="update-vscode-extensions-list"
+      shift
+      dotfiles_update_vscode_extensions_list_parse_requirements "$@"
       shift $#
       ;;
 
@@ -703,6 +890,51 @@ dotfiles_install_vscode_extension_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+dotfiles_update_vscode_extensions_list_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        dotfiles_update_vscode_extensions_list_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="update-vscode-extensions-list"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -726,6 +958,7 @@ run() {
     "symlink-vscode") dotfiles_symlink_vscode_command ;;
     "install-vscode-extensions") dotfiles_install_vscode_extensions_command ;;
     "install-vscode-extension") dotfiles_install_vscode_extension_command ;;
+    "update-vscode-extensions-list") dotfiles_update_vscode_extensions_list_command ;;
   esac
 }
 
